//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tablomüsteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tablomüsteriler()
        {
            this.tablosatislar = new HashSet<tablosatislar>();
        }
    
        public int müsteriid { get; set; }
        [Required(ErrorMessage = "Müşteri Adını Giriniz")]
        public string müsteriad { get; set; }
        [Required(ErrorMessage = " Müşteri Soyadını Giriniz")]
        public string müsterisoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tablosatislar> tablosatislar { get; set; }
    }
}
