//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tabloürünler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabloürünler()
        {
            this.tablosatislar = new HashSet<tablosatislar>();
        }
    
        public int ürünid { get; set; }
        public string ürünadi { get; set; }
        public string marka { get; set; }
        public Nullable<short> ürünkategori { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public Nullable<byte> stok { get; set; }
    
        public virtual tablokategoriler tablokategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tablosatislar> tablosatislar { get; set; }
    }
}
